name: Ensure Ticket Status

on:  
  pull_request:
    # Be aware you cannot use both branches and branches-ignore together 
    # Be aware this will skip if either the base or the compare branch is in here.
    branches-ignore:
      - master

jobs:  
  build:
    runs-on: ubuntu-latest
    name: Ensure Ticket exists and is Accepted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Perform Ticket Check
        # uses: forgeglobal/ensure-ticket-status@master
        # uses: ./ # Uses an action in the root directory
        
        with:
          # Defaults to jira unless specified here.
          team_to_project_system: |
            {
              "BAT": "pivotal"
            }
          team_to_project_id: |
            {
              "BAT": "2530518"
            }
          jira_api_user: ${{ secrets.NONPROD_JIRA_API_USER }}
          jira_api_token: ${{ secrets.NONPROD_JIRA_API_TOKEN }}
          # Pivotal only requires a token.
          pivotal_api_token: ${{ secrets.NONPROD_PIVOTAL_API_TOKEN }}
          teams: |
            [
              "BAT",
              "SHAR",
              "DATA",
              "TECOP"
            ]
          pull_request_compare_branch_name: ${{ github.event.pull_request.head.ref }}
          pull_request_base_branch_name: ${{ github.event.pull_request.base.ref }}
          